name: Build
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.5", "3.6", "3.7", "3.8"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        exclude:
          - os: "windows-latest"
            python: "3.4"
          - os: "windows-latest"
            python: "3.8"
          - os: "macos-latest"
            python: "3.4"
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make coverage
      - name: Run codecov
        uses: codecov/codecov-action@v1
